#! /usr/bin/env bash

machine=$(zenity --entry --title "Machine name" --text "Please enter the machine number that you wish to SSH to")

gnome-terminal -x bash -c "ssh -AX -o StrictHostKeyChecking=no csee137aer${machine}"
read
