#! /usr/bin/env bash

#########################################
machine_name=$(zenity --entry --title "Ansible Provisioning?" --text="Enter an IP that you would like to provision" --entry-text "IP Address")
echo "Provisioning the machine of your choice"
#########################################
zenity --warning --title "Make sure you add this line!" --text 'echo "machinename ansible_connection=ssh" > /etc/ansible/hosts '
#### Make sure that the line below is in the /etc/ansible/hosts file ####
# echo "machinename ansible_connection=ssh" > /etc/ansible/hosts

#########################################
echo "getting rid of host key crap"
ssh -t loud@$machine_name 'echo "host keys accepted now"'
#########################################

echo "Installing sysstaff auth"
ssh -t loud@$machine_name "sudo apt-get install lcsee-sysstaff-auth"

echo "Installing senior auth"
ssh -t loud@$machine_name "sudo apt-get install lcsee-senior-auth"

echo "rebooting system"
ssh -t loud@$machine_name "sudo reboot"
###########################################

######################
echo "sleeping for 2 minutes"
echo "2 mins left...."
sleep 1m
echo "1 mins left..."
sleep 1m
echo "done sleeping, back to work"
#######################

#########################################
cd /tmp
#git clone https://webgit.lcseecloud.net/ubuntu/loud-ubuntu-ansible.git
git archive --remote git@webgit.lcseecloud.net:ubuntu/loud-ubuntu-ansible.git --format tar --prefix=loud-ubuntu-ansible/ master | sudo tar xvf -
cd /tmp/loud-ubuntu-ansible
sed -i "s/localhost/${machine_name}/g" loud-test-all.yml
ansible-playbook -vvvv loud-test-all.yml
echo "The machine has been provisioned with loud"
##########################################

##########################################
cd /tmp
#git clone https://webgit.lcseecloud.net/ubuntu/lcsee-ubuntu-ansible.git
git archive --remote git@webgit.lcseecloud.net:ubuntu/lcsee-ubuntu-ansible.git --format tar --prefix=lcsee-ubuntu-ansible/ master | sudo tar xvf -
cd /tmp/lcsee-ubuntu-ansible
sed -i "s/localhost/${machine_name}/g" lcsee-sysstaff.yml
ansible-playbook -vvvv lcsee-sysstaff.yml
echo "The machine has been provisioned with lcsee"
##########################################

#########################################
echo "restarting machine"
ssh -A cumorris@$machine_name 'sudo reboot'
echo "machine reboot complete" 
#########################################

