#! /usr/bin/env bash
doshit(){
machine=$(zenity --entry --title "Machine name" --text "Please enter the machine number that you wish to SSH to")

gnome-terminal -x bash -c "ssh -AX cseesystems${machine}" 
}

doshit
