#!/usr/bin/ruby

require 'gtk3'

ICON_BUTTON = 24
BUTTON_SIZE = 64
BUTTON_LENGTH = 128
class SystemsHUD < Gtk::Window

    def initialize
	super
	home
    end

    def home
	home_window=Gtk::Window.new
	home_window.set_border_width 2
	home_window.title = ":)"
	home_window.set_size_request 30, 30
	home_window.set_decorated false
	home_window.set_resizable false
	home_window.set_keep_above true
	home_window.move(2000,2000)
	home_window.signal_connect "destroy" do
	    Gtk.main_quit
	end

	scripts_icon_image = Gdk::Pixbuf.new :file => File.expand_path("../icons/script_code_red.png", __FILE__)
	sites_icon_image = Gdk::Pixbuf.new :file => File.expand_path("../icons/page_white_world.png", __FILE__)
	ssh_icon_image = Gdk::Pixbuf.new :file => File.expand_path("../icons/application_osx_terminal.png", __FILE__)	

	scripts_icon = Gtk::Image.new :pixbuf => scripts_icon_image
	sites_icon = Gtk::Image.new :pixbuf => sites_icon_image
	ssh_icon = Gtk::Image.new :pixbuf => ssh_icon_image

	scripts_button = Gtk::Button.new()
	scripts_button.add(scripts_icon)
	scripts_button.set_size_request ICON_BUTTON, ICON_BUTTON
	scripts_button.signal_connect "clicked" do
	    scripts
	end

	sites_button = Gtk::Button.new()
	sites_button.add(sites_icon)
	sites_button.set_size_request ICON_BUTTON, ICON_BUTTON
	sites_button.signal_connect "clicked" do
	    sites
	end

	ssh_button = Gtk::Button.new()
	ssh_button.add(ssh_icon)
	ssh_button.set_size_request ICON_BUTTON, ICON_BUTTON
	ssh_button.signal_connect "clicked" do
	    ssh
	end
	    
	buttons_box = Gtk::Box.new :horizontal, 5
	buttons_box.add(scripts_button)
	buttons_box.add(sites_button)
	buttons_box.add(ssh_button)
	home_window.add(buttons_box)	
	home_window.show_all
    end

    def scripts
	scripts_window = Gtk::Window.new
	scripts_window.set_border_width 10
	scripts_window.override_background_color :normal, Gdk::RGBA::new(0,0,0,1)
	scripts_window.title = "Useful Scripts"
	scripts_window.set_default_size 300, 300
	scripts_window.set_window_position(Gtk::Window::Position::MOUSE)
	scripts_window.set_keep_above true	
	infco_button = Gtk::Button.new(:label => "infco")
	infco_button.set_size_request BUTTON_SIZE, BUTTON_SIZE
	infco_button.signal_connect "clicked" do
	    infcocheck = File.expand_path("../infco-check", __FILE__)	    
	    system "gnome-terminal -e #{infcocheck}"	    
	    scripts_window.destroy	    
	end
	
	buttons_box = Gtk::Box.new :vertical, 5
	buttons_box.add(infco_button)
	scripts_window.add(buttons_box)
	scripts_window.show_all
    end

    def sites
	sites_window = Gtk::Window.new
	sites_window.set_border_width 10
	sites_window.override_background_color :normal, Gdk::RGBA::new(0,0,0,1)
	sites_window.title = "Useful Websites"
	sites_window.set_default_size 300, 300
	sites_window.set_window_position(Gtk::Window::Position::MOUSE)
	sites_window.set_resizable false
	sites_window.set_keep_above true

	nagios_server_button = Gtk::Button.new(:label => "server nagios")
	nagios_server_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	nagios_server_button.signal_connect "clicked" do
	    webpage("https://nagios.lcsee.wvu.edu/nagios3")
	    sites_window.destroy	    
	end
	nagios_lab_button = Gtk::Button.new(:label => "lab nagios")
	nagios_lab_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	nagios_lab_button.signal_connect "clicked" do
	    webpage("https://labnagios.lcsee.wvu.edu/nagios3")
	    sites_window.destroy
	end	    
	infco_button = Gtk::Button.new(:label => "infco")
	infco_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	infco_button.signal_connect "clicked" do
	    webpage("https://infco.lcseecloud.wvu.edu/infco")		
	    sites_window.destroy
	end
	faq_button = Gtk::Button.new(:label => "faq")
	faq_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	faq_button.signal_connect "clicked" do
	    webpage("https://wiki.lcsee.wvu.edu/lcseehelpdesk/faq/")
	    sites_window.destroy
	end
	lsr_button = Gtk::Button.new(:label => "lsr")
	lsr_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	lsr_button.signal_connect "clicked" do
	    webpage("https://lcsee.wvu.edu/lcsee-docs")
	    sites_window.destroy
	end
	outlook_button = Gtk::Button.new(:label => "outlook")
	outlook_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	outlook_button.signal_connect "clicked" do
	    webpage("http://login.microsoftonline.com")
	    sites_window.destroy
	end
	svn_button = Gtk::Button.new(:label => "svn")
	svn_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	svn_button.signal_connect "clicked" do
	    webpage("https://loud.lcsee.wvu.edu/loud")
	    sites_window.destroy
	end
	g_plus_button = Gtk::Button.new(:label => "g+")
	g_plus_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	g_plus_button.signal_connect "clicked" do
	    webpage("https://plus.google.com/u/0/communities/103766111706586762839")
	    sites_window.destroy
	end
	spotify_button = Gtk::Button.new(:label => "spotify")
	spotify_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	spotify_button.signal_connect "clicked" do
	    webpage("http://play.spotify.com")
	    sites_window.destroy
	end
	slack_button = Gtk::Button.new(:label => "slack")
	slack_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	slack_button.signal_connect "clicked" do
	    webpage("https://lcseesystems.slack.com")
	    sites_window.destroy
	end
	wiki_button = Gtk::Button.new(:label => "wiki")
	wiki_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	wiki_button.signal_connect "clicked" do
	    webpage("https://wiki.lcsee.wvu.edu/sysstaff/")
	    sites_window.destroy
	end
	rt_button = Gtk::Button.new(:label => "rt002")
	rt_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	rt_button.signal_connect "clicked" do
	    webpage("https://rt002.lcsee.wvu.edu/request-tracker/")
	    sites_window.destroy
	end
	whentowork_button = Gtk::Button.new(:label => "whentowork")
	whentowork_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	whentowork_button.signal_connect "clicked" do
	    webpage("https://whentowork.com/login")
	    sites_window.destroy
	end
	webgit_button = Gtk::Button.new(:label => "webgit")
	webgit_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	webgit_button.signal_connect "clicked" do
	    webpage("https://webgit.lcseecloud.net")
	    sites_window.destroy
	end
	github_button = Gtk::Button.new(:label => "github")
	github_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	github_button.signal_connect "clicked" do
	    webpage("https://github.com")
	    sites_window.destroy
	end
	whatsup_button = Gtk::Button.new(:label => "don't click")
	whatsup_button.set_size_request BUTTON_LENGTH, BUTTON_SIZE
	whatsup_button.signal_connect "clicked" do
	    webpage("http://heyyeyaaeyaaaeyaeyaa.com/")
	    sites_window.destroy
	end
	
	buttons_box = Gtk::Box.new :vertical, 5
	buttons_sub_1 = Gtk::Box.new :horizontal, 5
	buttons_sub_2 = Gtk::Box.new :horizontal, 5
	buttons_sub_3 = Gtk::Box.new :horizontal, 5
	buttons_sub_4 = Gtk::Box.new :horizontal, 5
	
	buttons_sub_1.add(slack_button)
	buttons_sub_1.add(rt_button)
	buttons_sub_1.add(outlook_button)
	buttons_sub_1.add(lsr_button)
	buttons_sub_2.add(nagios_lab_button)
	buttons_sub_2.add(nagios_server_button)
	buttons_sub_2.add(g_plus_button)
	buttons_sub_2.add(faq_button)
	buttons_sub_3.add(infco_button)
	buttons_sub_3.add(whentowork_button)
	buttons_sub_3.add(svn_button)
	buttons_sub_3.add(wiki_button)
	buttons_sub_4.add(webgit_button)
	buttons_sub_4.add(github_button)
	buttons_sub_4.add(spotify_button)
	buttons_sub_4.add(whatsup_button)

	buttons_box.add(buttons_sub_1)
	buttons_box.add(buttons_sub_2)
	buttons_box.add(buttons_sub_3)
	buttons_box.add(buttons_sub_4)

	sites_window.add(buttons_box)
	sites_window.show_all

    end

    def ssh
	ssh_window = Gtk::Window.new
	ssh_window.set_border_width 10
	ssh_window.title = "ssh"
	ssh_window.set_window_position(Gtk::Window::Position::MOUSE)
	ssh_window.set_default_size 300, 300
	ssh_window.set_resizable false
	ssh_window.set_keep_above true

	nagios001_button = Gtk::Button.new(:label => "Nagios001")
	nagios001_button.set_size_request BUTTON_SIZE, BUTTON_SIZE
	nagios001_button.signal_connect "clicked" do
	    sshlink("nagios001")
	    ssh_window.destroy
	end	    
	tnode_button = Gtk::Button.new(:label => "tnode")
	tnode_button.set_size_request BUTTON_SIZE, BUTTON_SIZE
	tnode_button.signal_connect "clicked" do
	    sshlink("tnode001")
	    ssh_window.destroy
	end	    
	nodes_button = Gtk::Button.new(:label => "Nodes")
	nodes_button.set_size_request BUTTON_SIZE, BUTTON_SIZE
	nodes_button.signal_connect "clicked" do
	    nodes
	    ssh_window.destroy
	end
	systems_machines_button = Gtk::Button.new(:label => "Systems machines")
	systems_machines_button.set_size_request BUTTON_SIZE, BUTTON_SIZE
	systems_machines_button.signal_connect "clicked" do
	    sysstaff_ssh = File.expand_path("../systems-ssh",__FILE__)
	    system("gnome-terminal -e #{sysstaff_ssh} &")
	    ssh_window.destroy	    
	end
	aer137_button = Gtk::Button.new(:label => "AER 137")
	aer137_button.set_size_request BUTTON_SIZE, BUTTON_SIZE
	aer137_button.signal_connect "clicked" do
            ssh137 = File.expand_path("../137ssh",__FILE__)
	    system("gnome-terminal -e #{ssh137} &")
	    ssh_window.destroy
        end
	shell_button = Gtk::Button.new(:label => "Shell")
	shell_button.set_size_request BUTTON_SIZE, BUTTON_SIZE
	shell_button.signal_connect "clicked" do
	    sshlink("shell")
	    ssh_window.destroy	    
 	end
	prop_button = Gtk::Button.new(:label => "Proprietary")
	prop_button.set_size_request BUTTON_SIZE, BUTTON_SIZE
	prop_button.signal_connect "clicked" do
	    sshlink("proprietary")
	    ssh_window.destroy
	end
	lpreciseshell_button = Gtk::Button.new(:label => "lprecise")
	lpreciseshell_button.set_size_request BUTTON_SIZE, BUTTON_SIZE
	lpreciseshell_button.signal_connect "clicked" do
	    sshlink("lpreciseshell001")
	    ssh_window.destroy
	end
	buttons_box = Gtk::Box.new :vertical, 5
	
	buttons_box.add(shell_button)
	buttons_box.add(prop_button)
	buttons_box.add(systems_machines_button)
	buttons_box.add(aer137_button)
	buttons_box.add(nagios001_button)
	buttons_box.add(nodes_button)
	buttons_box.add(tnode_button)

	ssh_window.add(buttons_box)
	ssh_window.show_all
		
    end

    def nodes()
        nodes_window = Gtk::Window.new
    	nodes_window.set_border_width 10
	nodes_window.override_background_color :normal, Gdk::RGBA::new(0,0,0,1)
	nodes_window.title = "Nodes"
	nodes_window.set_default_size 300, 300
	nodes_window.set_window_position(Gtk::Window::Position::MOUSE)
	nodes_window.set_keep_above true
	
	node007_button = Gtk::Button.new(:label => "node007")
	node007_button.set_size_request BUTTON_SIZE, BUTTON_SIZE
	node007_button.signal_connect "clicked" do
		    sshlink("node007")
	            nodes_window.destroy
        end
        
        
	buttons_box = Gtk::Box.new :vertical, 5
	buttons_box.add(node007_button)
        
	nodes_window.add(buttons_box)
	nodes_window.show_all

    end

    def webpage(url)
	link = url
	system "chromium-browser -new-tab #{link} &"
    end

    def sshlink(location)
	machine = location
	if machine === "shell" || machine === "proprietary" || machine === "lpreciseshell001"
	    system "gnome-terminal -e 'ssh -AXp 20110 #{ENV['USER']}@#{machine}.lcsee.wvu.edu'"
	else
	    system "gnome-terminal -e 'ssh -AX #{ENV['USER']}@#{machine}.lcsee.wvu.edu'"
	end
    end

end

Gtk.init
window = SystemsHUD.new
Gtk.main
